FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source code
COPY . .

# Build TypeScript
RUN npm run build

# Expose port and start the server
EXPOSE 3000
CMD [ "npm", "start" ]